version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
    networks:
      - cctv-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - cctv-network
    restart: unless-stopped

networks:
  cctv-network:
    driver: bridge
