services:
  backend:
    build: ./backend
    container_name: my_backend
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./backend/cctv.json:/app/cctv.json
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8000/cctv || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  frontend:
    build: ./frontend
    container_name: my_frontend
    restart: always
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - '3000:80'
    environment:
      # frontend di browser pakai proxy → cukup set base path /api
      VITE_BACKEND_API_URL: '/api'

volumes:
  db_data:
